### ISSUE TITLE
overwriting module name in example notebook

### ISSUE THREAD

**Issue by grovduck** [fitoprincipe/geebap#2]
@fitoprincipe - super cool tool.  I've just started playing around with it.  One thing you might want to consider changing is this line in your `Best_Available_Pixel_Composite,ipynb` script:

    bap = bap.Bap(year=2000, range=(0, 0),
              season=a_season,
              masks=(cld_mask,),
              scores=(doy, sat, atm_op, dist, out, maskper, ind),
              filters=(filt_cld, filt_mask))

If a user steps through the code sequentially, but then comes back and changes reruns this block, the variable name `bap` has now clobbered the module name.  Minor annoyance, but might trip up some people.  Thanks for your work on this.

**Comment by fitoprincipe** [comment]
Hi @grovduck, you are totally right! Thank you! :+1:
